# Generated by Django 4.2.1 on 2024-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('is_club_member', models.BooleanField(default=False)),
                ('club_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_purpose', models.TextField()),
                ('event_scope', models.TextField()),
                ('event_date', models.DateField()),
                ('event_duration', models.TimeField()),
            ],
        ),
    ]
